language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache

jobs:
  include:
    - # require the branch name to be master
      if: branch = master
      env: NODE_ENV=test
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn
        - yarn bootstrap
      script:
        - yarn lint
        - yarn test
        - NODE_ENV=production yarn build
        - yarn semantic-release --extends build/publish-config/src/index.js
  include:
    - # require branch is PR
      if: type IN (pull_request)
      env: NODE_ENV=test
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn
        - yarn bootstrap
      script:
        - yarn lint
        - yarn test
