import {setOpacity, toRgbaString} from '@andrew-codes/color-functions';

export default {
    _name: 'Test Theme',
    altColor: '#ffa500',
    basicColor: '#00ffff',
    basicFontFamily: '\'Proxima Nova\', \'Lucida Sans Unicode\', \'Lucida Grande\', sans-serif',
    baseIconSize: 24,
    boldFont: 600,
    borderPrimaryColor: '#000',
    darkInverseColor: '#fff',
    disabledPrimaryColor: '#808080',
    errorPrimaryColor: '#ffc0cb',
    errorSecondaryColor: '#ffc0cd',
    fieldBorderColor: '#808080',
    focusedPrimaryColor: '#00ffff',
    focusedSecondaryColor: toRgbaString(setOpacity('#00ffff', 0.5)),
    gutter: 8,
    importantColor: '#f99643',
    largeFontSize: 22,
    largeGutter: 12,
    largeLineHeight: 2.285,
    lightInverseColor: '#030303',
    mediumFontSize: 16,
    normalBackground: '#fff',
    normalLineHeight: 1.285,
    normalRadius: 3,
    requiredPrimaryColor: '#ffc0cb',
    pendingPrimaryColor: '#ffff00',
    smallFontSize: 14,
    smallGutter: 6,
    textPrimaryColor: '#030303',
    textSecondaryColor: '#030303',
    textDisabledColor: '#808080',
    xLargeFontSize: 24,
    xLargeGutter: 16,
    xMediumFontSize: 18,
    xSmallFontSize: 8,
    xxSmallGutter: 3
};
